# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://felipeblini,net" # the base hostname & protocol for your site

title:  Felipe Blini - Angular Developer and Consultant
email: contato@felipeblini.net
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  
# for to build the multilanguage menu
t:
  pt:
    country: br
    lang: pt
    pages:
        about:
            name: "Sobre"
            url: "/about/"
        treinamentos:
            name: "Treinamentos"
            url: "/treinamentos"
  en:
    country: us
    lang: en
    pages:
        about:
            name: "About"
            url: "/en/about/"
        trainnings:
            name: "Trainnings"
            url: "/en/treinamentos"

theme:
    # Icons
    rss: true
    email_address: # Full email address, e.g. "sam@example.com"
    behance:
    bitbucket:
    dribbble:
    facebook:
    flickr:
    github: "felipeblini"
    google_plus:
    instagram:
    linkedin:  # Full URL
    pinterest:
    reddit:
    soundcloud:
    stack_exchange:  # Full URL
    steam:
    tumblr:
    twitter: "blini3"
    wordpress:
    youtube:

    # Scripts
    google_analytics: # Tracking ID, e.g. "UA-000000-01"
    disqus_shortname: felipeblini
    katex: false # Enable if using math markup
    fontawesome: true

    # Localization strings
    str_follow_on: "Follow on"
    str_rss_follow: "Follow RSS feed"
    str_email: "Email"
    str_next: "Next"
    str_prev: "Prev"
    str_continue_reading: "Continue reading"

    # Colours, typography and padding
    # Open the "_sass > base" folder, and open "_variables.scss"
    google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

    # Post navigation
    post_navigation: true

# PAGINATION
# paginate: 5
# paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
permalink: /:title
highlighter: rouge
sass:
    sass_dir: _sass
    style: :compressed
# gems: [jekyll-paginate]